package com.alenskaya.fakecalls.domain.calls

import com.alenskaya.fakecalls.domain.BaseResponse
import com.alenskaya.fakecalls.domain.DatabaseError
import com.alenskaya.fakecalls.domain.calls.model.CreateNewCallRequest
import com.alenskaya.fakecalls.domain.calls.model.SavedCall
import com.alenskaya.fakecalls.domain.calls.model.UpdateCallRequest

/**
 * Repository for handling calls data.
 */
interface CallsRepository {

    /**
     * Request to save a new call with data from [createNewCallRequest].
     * @return [BaseResponse.Success] with autogenerated call id in case of success, [BaseResponse.Error] otherwise
     */
    suspend fun createCall(
        createNewCallRequest: CreateNewCallRequest
    ): BaseResponse<Int, DatabaseError>

    /**
     * Requests list of saved calls.
     * @return [BaseResponse.Success] with sorted by date list of calls as a payload in case of success,
     * [BaseResponse.Error] otherwise
     */
    suspend fun getSavedCalls(): BaseResponse<List<SavedCall>, DatabaseError>

    /**
     * Requests call with given id
     * @param callId - call identifier.
     * @return [BaseResponse.Success] with saved call as a payload in case of success,
     * [BaseResponse.Error] otherwise
     */
    suspend fun getSavedCallById(callId: Int): BaseResponse<SavedCall, DatabaseError>

    /**
     * Updates call according to [updateCallRequest].
     * @return empty [BaseResponse.Success] in case of success, [BaseResponse.Error] otherwise.
     */
    suspend fun updateCall(
        updateCallRequest: UpdateCallRequest
    ): BaseResponse<Unit, DatabaseError>

    /**
     * Updates status of call with id = [callId] to COMPLETED.
     * @return empty [BaseResponse.Success] in case of success, [BaseResponse.Error] otherwise.
     */
    suspend fun markCallAsCompleted(callId: Int): BaseResponse<Unit, DatabaseError>
}
